version: 2

# Only enable cargo, turn off npm from wasm example
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # todo: if only this worked, see https://github.com/dependabot/dependabot-core/issues/4009
    # only tell us if there's a new 'breaking' change we could upgrade to
    # versioning-strategy: increase-if-necessary
    # disable regular version updates, security updates are unaffected
    open-pull-requests-limit: 0
