version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/examples/wasm_github_fetch"
    schedule:
      interval: "daily"
    # disable regular version updates, security updates are unaffected
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/examples/wasm_github_fetch"
    schedule:
      interval: "monthly"
