package reqwest:wasi;

world http-client {
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/poll@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;
}
